### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by ajurna** [antoinemartin/django-windows-tools#17]
Is there any chance that this will be updated to support python 3?

**Comment by mrbean-bremen** [comment]
Actually it should work with Python 3 (see PR #14). Do you have specific problems?

**Comment by ajurna** [comment]
specifically multiprocessing.forking is no longer in the std library and this is used in service.py.
i am using python 3.6.

**Comment by mrbean-bremen** [comment]
You are right - there is no multiprocessing.forking in python 3. 
I currently don't have a test system (and may not have for some time), but I tried to fix the problem (mainly by using `spawn` instead of `forking` in python 3). Could you please check if this works for you? As soon as that works, I will release a new version.

**Comment by ajurna** [comment]
i wont have time to check until monday at least. ill see what i can do next week.

**Comment by mrbean-bremen** [comment]
Did you find time to test this?

**Comment by mrbean-bremen** [comment]
@ajurna : any news here?

**Comment by mrbean-bremen** [comment]
Generally seems to work with Python3 (though there are unrelated problems with celery, and with virtual environments).
Closing this, reopen at will.
